Update index.html
htmlacademy-htmlcss/1421565-technomart-29 pull request #2
Opened 2020-09-21 14:19 UTC by zhenya-s

Добавила верстку главной страницы

2020-09-21 15:52 UTC, VadimCpp requested changes

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +      <a href="#">Техномарт</a>
Перенести наверх "поиск", "закладки", "корзина"

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +          <li><a href="catalog.html">Каталог</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +          <li><a href="blank.html">Новости</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +          <li><a href="blank.html">Спецпредложение</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +          <li><a href="blank.html">Доставка</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +        <li><a href="blank.html">Корзина</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +        <li><a href="blank.html">Оформить заказ</a></li>
Почему ссылка нерабочая?

2020-09-21 15:52 UTC, VadimCpp commented on index.html
> +        <ul>
Такая разметка не будет работать.

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +      <h1>Техномарт</h1>
не заголовок

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +      <p>Интернет-магазин строительных материалов и инструментов для ремонта</p>
почему это находится после лого? По макету этот элемент находится после кнопки "оформить заказ". Макеты читаем сверху вниз слева направо. И это не просто абзац. Подумай какой тег тут лучше использовать

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        <p>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</p>
для адреса есть свой тег. погугли

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
форматирование. лишняя пустая строка

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +          <li><a href="blank.html">Оформить заказ</a></li>
лучше везде оставить пустой href

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        </section>
снова секция не на своем месте. Она должна находится между адресом и навигацией

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишнее

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <p>На любой вкус</p>
посмотри внимательно тз и подумай какой тег тут будет лучше

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <p>На все случаи</p>
тоже самое

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <p>Для стройки</p>
тоже самое

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <p>На 350 товаров</p>
тоже самое

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <p>Бесплатно</p>
тоже самое

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        <figure>
лишний тег. И ссылкой тут является только кнопка открыть каталог, изображение не должно быть в ссылке

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        </figure>
добавить скрытый слой

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            <figure>
лишний

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +            </figure>
посмотри макет, они стилизованы по-разному. А у тебя текст находится внутри одного тега. Как будешь в дальнейшем стилизовывать?) надо поменять структуру в данном компоненте

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +          </li>
как в первой карточке

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +          <li><a href="blank.html">Metabo</a></li>
а где сами картинки?)

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +          <img src="https://via.placeholder.com/150x100" alt="">
это не контактное изображение, а декоративное. Декоративные элементы в разметку не вставляются.

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +      </section>
добавить скрытые слои

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        <p>Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для ремонта и строительства не оставит равнодушными любителей сэкономить на гастарбайтерах.<br><br>
плохая практика юзать 2 подряд br. Лучше закончи тут один абзац и начни другой

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишняя

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        <figure>
давай без figure

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        </ul>
а где этот элемент?
<img width="266" alt="image" src="https://user-images.githubusercontent.com/45230482/94116488-cb040380-fe53-11ea-979f-58dc8fe76c0b.png">

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишняя

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +    <br>
зачем? надо убрать

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +      <p>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8+7 (812) 555-05-55</p>
как в хедере

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишние

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишняя

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +
лишние

2020-09-24 07:54 UTC, atmirataev commented on index.html
лишние

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        htmlacademy.ru</p>
тут ссылка

2020-09-24 07:54 UTC, atmirataev commented on index.html
> +        mail@htmlacademy.ru</p>
тут ссылка

2020-09-24 14:00 UTC, atmirataev reviewed
Осталось немного :)

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +          <address>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</address></p>
</p> забыла убрать

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <img src="https://via.placeholder.com/620x266" alt="Перфоратор"><br>
br лишний

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <a href="catalog.html"><button type="button">Открыть каталог</button>
и ссылка и кнопка все вместе) тогда убери button

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <br>
лишнее

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <br>
как в 1-м слайде

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +            <a href="">25500 Р.</a>
тут ссылкой будет вся карточка, а тут обычный абзац. В alt не хватает пробела

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +            <a href="">15500 Р.</a>
тоже самое

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +            <a href="">25500 Р.</a>
тоже самое

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <a href=""><button type="button">Подробнее о компании</button></a>
оставь только ссылку

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <button type="button">Заблудились? Напишите нам!</button>
тут тоже лучше ссылку

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <a href="index.html">Техномарт</a>
зачем ссылку на саму себя? тут надо оставить пустой href

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +      <p>+7 (812) 555-05-55</p>
тут сделай как в хедере

2020-09-24 14:00 UTC, atmirataev commented on index.html
> +        <a href="htmlacademy.ru">htmlacademy.ru</a>
не посмотрела внимательно ТЗ. Ссылка другая

2020-09-29 10:54 UTC, merged